### ISSUE TITLE
Cannot run example

### ISSUE THREAD

**Issue by RockerFlower** [jbms/beancount-import#13]
```
Listening at http://127.0.0.1:8101
Traceback (most recent call last):
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/webserver.py", line 489, in _handle_reconciler_loaded
    loaded_reconciler = loaded_future.result()
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/thread_helpers.py", line 13, in wrapper
    f.set_result(fn(*args, **kwargs))
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/reconcile.py", line 380, in __init__
    self._load_sources()
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/reconcile.py", line 434, in _load_sources
    for spec in self.reconciler.options['data_sources']
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/reconcile.py", line 434, in <listcomp>
    for spec in self.reconciler.options['data_sources']
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/source/__init__.py", line 318, in load_source
    m = importlib.import_module(source_spec.pop('module'))
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/source/ofx.py", line 434, in <module>
    from beancount.ingest.importers.ofx import parse_ofx_time, find_child
ModuleNotFoundError: No module named 'beancount.ingest.importers.ofx'
> /Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount_import/source/ofx.py(434)<module>()
-> from beancount.ingest.importers.ofx import parse_ofx_time, find_child
(Pdb)
```

**Comment by jbms** [comment]
Sorry for the long delay.  I'm not able to reproduce this problem, and I do still see the beancount.ingest.importers.ofx module in the upstream repository.
https://bitbucket.org/blais/beancount/src/default/beancount/ingest/importers/ofx.py

Perhaps try reinstalling the beancount pip package?

**Comment by TiraelSedai** [comment]
@RockerFlower do you still experiencing this issue?
