### ISSUE TITLE
matching.py: comparison with NoneType

### ISSUE THREAD

**Issue by Zburatorul** [jbms/beancount-import#192]
```Got next candidates in 0.0186 seconds
Traceback (most recent call last):
  File "/home/zburatorul/beancount-import/beancount_import/webserver.py", line 626, in handle_select_candidate
    self.get_next_candidates(new_pending=True)
  File "/home/zburatorul/beancount-import/beancount_import/webserver.py", line 547, in get_next_candidates
    self.next_candidates, index, self.skip_ids = loaded_reconciler.get_next_candidates(
  File "/home/zburatorul/beancount-import/beancount_import/reconcile.py", line 919, in get_next_candidates
    return self._make_candidates_from_import_result(
  File "/home/zburatorul/beancount-import/beancount_import/reconcile.py", line 871, in _make_candidates_from_import_result
    match_results = matching.get_extended_transactions(
  File "/home/zburatorul/beancount-import/beancount_import/matching.py", line 1784, in get_extended_transactions
    maybe_extend_candidate(initial_transaction, initial_transaction, level=0)
  File "/home/zburatorul/beancount-import/beancount_import/matching.py", line 1768, in maybe_extend_candidate
    do_extend_candidate(transaction, level)
  File "/home/zburatorul/beancount-import/beancount_import/matching.py", line 1775, in do_extend_candidate
    for new_transaction, matching_transaction in get_single_step_extended_transactions(
  File "/home/zburatorul/beancount-import/beancount_import/matching.py", line 1679, in get_single_step_extended_transactions
    for sp in results:
  File "/home/zburatorul/beancount-import/beancount_import/matching.py", line 359, in search_postings
    while db[s.stop-1].number <= upper:
TypeError: '<=' not supported between instances of 'NoneType' and 'decimal.Decimal'
got error
> /home/zburatorul/beancount-import/beancount_import/matching.py(359)search_postings()
-> while db[s.stop-1].number <= upper:
```

Meanwhile:

```(Pdb) db[s.stop-1]
SearchPosting(
    number=None, 
    key=(140719510656544, 140719404504000), 
    entry=Transaction(meta=OrderedDict([('amazon_order_id', '112-5100831-5442647'), ('amazon_account', 'zburatorul')]), date=datetime.date(2023, 2, 4), flag='*', payee='Amazon.com', narration='some narration', tags=frozenset(), links=frozenset(), postings=[Posting(account='Expenses:FIXME:A', units=5.49 USD, cost=None, price=None, flag=None, meta=OrderedDict([('amazon_item_description', 'item desc'), ('amazon_seller', 'COLORWORK'), ('amazon_item_condition', 'New'), ('shipped_date', datetime.date(2023, 2, 5)), ('amazon_item_quantity', Decimal('1'))])), 
    Posting(account='Expenses:FIXME:A', units=-1.55 USD, cost=None, price=None, flag=None, meta=OrderedDict([('amazon_invoice_description', 'Your Coupon Savings')])), Posting(account='Expenses:FIXME:A', units=1.41 USD, cost=None, price=None, flag=None, meta=OrderedDict([('amazon_invoice_description', 'Sales Tax')])), Posting(account='Expenses:FIXME', units=-1.35 USD, cost=None, price=None, flag=None, meta=OrderedDict([('amazon_posttax_adjustment', 'Gift Card Amount')])), 
    Posting(account='Expenses:FIXME', units=0.00 USD, cost=None, price=None, flag=None, meta=OrderedDict([('transaction_date', datetime.date(2023, 2, 4)), ('amazon_credit_card_description', 'cc desc')]))]), mp=MatchablePosting(posting=Posting(account='Expenses:FIXME', units=0.00 USD, cost=None, price=None, flag=None, meta=OrderedDict([('transaction_date', datetime.date(2023, 2, 4)), ('amazon_credit_card_description', 'cc desc')])), weight=0.00 USD, source_postings=(Posting(account='Expenses:FIXME', units=0.00 USD, cost=None, price=None, flag=None, meta=OrderedDict([('transaction_date', datetime.date(2023, 2, 4)), ('amazon_credit_card_description', 'cc desc')])),)))
```

@xentac , could you to take a look at this for me please?

**Comment by xentac** [comment]
Do you have a file that consistently reproduces this? I used to get it occasionally when I had a bug in my code, but I couldn't reproduce it with any of the tests.

The hard part is the SearchPosting is created at a way different point. If you could give me the repr() of the MatchablePosting given to _search_posting, when get_posting_weight returns None, I might be able to figure out what the code ought to do.

**Comment by Zburatorul** [comment]
I've tried to catch the MatchablePosting you mention, but none show up.
See how I tried:

```
diff --git a/beancount_import/matching.py b/beancount_import/matching.py
index 3eb60aa..e68dbde 100644
--- a/beancount_import/matching.py
+++ b/beancount_import/matching.py
@@ -154,6 +154,8 @@ DEBUG = False
 
 MAX_AGGREGATE_POSTINGS = 30000
 
+bad_mps = []
+
 IsClearedFunction = Callable[[Posting], bool]
 MatchGroupKey = NamedTuple('MatchGroupKey', [('currency', str),
                                              ('is_positive', bool)])
@@ -272,6 +274,9 @@ class PostingDatabase(object):
     def _search_posting(self, entry: Transaction, mp: MatchablePosting):
         pw = get_posting_weight(mp.posting)
         number = None
+        if pw is None:
+            global bad_mps
+            bad_mps.append(mp)
         if pw:
             number = pw.number
         return SearchPosting(
@@ -317,6 +322,8 @@ class PostingDatabase(object):
         for mp in mps:
             weight = get_posting_weight(mp.posting)
             if weight is None:
+                global bad_mps
+                bad_mps.append(mp)
                 continue
             if negate:
                 weight = -weight

```

The list was empty when the Pdb shell popped during the crash.
I have two Amazon invoices that cause the crash (one with a single posting, the other with two). There's nothing special about them. I have others like them.

Any other suggestions?

**Comment by xentac** [comment]
Rereading the stack trace, it's actually finding a None number, not the entire weight. You really only have to add it to after the `if weight is None` check in `search_postings`.

You also don't need the `global bad_mps`. You're only referencing a global, not trying to set it.

**Comment by Zburatorul** [comment]
I think I found it.  The Amazon source correctly produces postings with a Decimal(0) amount sometimes. 
`bool(Amount(D(0), 'USD'))` evaluates to False, which resulted in line 274 setting `number = None`.
This is the fix:

```
diff --git a/beancount_import/matching.py b/beancount_import/matching.py
index 3eb60aa..7a1523f 100644
--- a/beancount_import/matching.py
+++ b/beancount_import/matching.py
@@ -265,14 +265,14 @@ class PostingDatabase(object):
     def _date_currency_key(self, entry: Transaction, mp: MatchablePosting) -> DateCurrencyKey:
         pw = get_posting_weight(mp.posting)
         currency = ""
-        if pw:
+        if pw is not None:
             currency = pw.currency
         return (_date_key(entry, mp), currency)
 
     def _search_posting(self, entry: Transaction, mp: MatchablePosting):
         pw = get_posting_weight(mp.posting)
         number = None
-        if pw:
+        if pw is not None:
             number = pw.number
         return SearchPosting(
             number=number,
```

**Comment by xentac** [comment]
Nice catch! I support this PR!
