### ISSUE TITLE
Fidelity OFX has two CUSIP per ticker

### ISSUE THREAD

**Issue by scanta2** [jbms/beancount-import#205]
Lately my ofx imports from Fidelity fail because the same ticker appears in the ofx file with two CUSIP identifiers. Has anybody else seen the same issue? Is it possible to have multiple cusip metadata values?

Thanks

**Comment by ioniua** [comment]
I wasn't sure why it wasn't working for me, but this could be the reason. Here is the error I am getting:

```python
Listening at http://0.0.0.0:8101
Traceback (most recent call last):
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/webserver.py", line 514, in _handle_reconciler_loaded
    loaded_reconciler = loaded_future.result()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/thread_helpers.py", line 13, in wrapper
    f.set_result(fn(*args, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/reconcile.py", line 380, in __init__
    self._load_sources()
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/reconcile.py", line 437, in _load_sources
    sources = self.sources = [
                             ^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/reconcile.py", line 438, in <listcomp>
    load_source(spec, log_status=self.reconciler.log_status)
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/__init__.py", line 334, in load_source
    return m.load(source_spec, log_status=log_status)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/paypal.py", line 664, in load
    return PaypalSource(log_status=log_status, **spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/paypal.py", line 353, in __init__
    super().__init__(link_prefix=prefix + '.', **kwargs)
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/link_based_source.py", line 11, in __init__
    super().__init__(**kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/__init__.py", line 258, in __init__
    super().__init__(**kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
> /home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/__init__.py(258)__init__()
-> super().__init__(**kwargs)  # type: ignore
``` 

The only way for me to get it to work is by reverting back to before this [commit](https://github.com/jbms/beancount-import/commit/b8a78069f515519e27b42450cb525278a50b12bb) that added options importing.

**Comment by ioniua** [comment]
So I did a fresh install of python and all packages, including beancount-import, and am now getting a different error on treasuries. Any idea what's going on?

```python
Traceback (most recent call last):
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/webserver.py", line 514, in _handle_reconciler_loaded
    loaded_reconciler = loaded_future.result()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/thread_helpers.py", line 13, in wrapper
    f.set_result(fn(*args, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/reconcile.py", line 396, in __init__
    all_source_results = self._prepare_sources()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/reconcile.py", line 520, in _prepare_sources
    source.prepare(self.editor, source_results)
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/ofx.py", line 1535, in prepare
    state.get_accounts_and_entries()
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/ofx.py", line 1382, in get_accounts_and_entries
    statement.get_entries(self)
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/ofx.py", line 1227, in get_entries
    security = get_security(raw.uniqueid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/ofx.py", line 837, in get_security
    if ticker.startswith("912"):
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
> /home/ioniua/.local/lib/python3.11/site-packages/beancount_import/source/ofx.py(837)get_security()
-> if ticker.startswith("912"):
(Pdb)

```

**Comment by Zburatorul** [comment]
Yes @scanta2  I have this issue too. We could have a special meta key that would contain all the cusips of a given commodity. Then the importer would at least propose correct candidates. 

I have a little diff that maybe fixes this. Can you try this?
```diff --git a/beancount_import/reconcile.py b/beancount_import/reconcile.py
index 6f2ab25..d22db83 100644
--- a/beancount_import/reconcile.py
+++ b/beancount_import/reconcile.py
@@ -688,6 +688,8 @@ class LoadedReconciler(object):
                         or self.transactions_since_last_balance[entry.account] < 10:
                             self.reconciler.log_status(f"Skipping balance entry for {entry.account} on {entry.date}")
                             continue
+                    if entry.amount is None:
+                        raise Exception(f"entry.amount is none.  {entry}")
                     key = (entry.date, entry.account, entry.amount.currency)
                     if key in self.balance_entries:
                         continue
diff --git a/beancount_import/source/ofx.py b/beancount_import/source/ofx.py
index 943d62a..5f92940 100644
--- a/beancount_import/source/ofx.py
+++ b/beancount_import/source/ofx.py
@@ -926,6 +926,12 @@ class ParsedOfxStatement(object):
             sec = securities_map[unique_id]
             ticker = sec.ticker
             # Treasury bill and bond start with 912
+            if ticker is None:
+                print(f"Unique_ID: {unique_id}  Sec:  {sec}")
+                results.add_error(
+                    f"Unique_ID: {unique_id}  Sec:  {sec}")
+                for k, v in commodities_by_cusip.items():
+                    results.add_error(f"{k} -> {v}")
             if ticker.startswith("912"):
                 # Prepend "T" to make it a valid ticker
                 ticker = "T" + ticker
@@ -1525,7 +1531,8 @@ class PrepareState(object):
                     matched.setdefault(full_fitid, []).append((entry, posting))
             elif isinstance(entry, Commodity):
                 if CUSIP_KEY in entry.meta:
-                    commodities_by_cusip[entry.meta[CUSIP_KEY]] = entry.currency
+                    for cusip in entry.meta[CUSIP_KEY].split("|"):
+                        commodities_by_cusip[cusip] = entry.currency
                 if EQUIVALENT_CURRENCY in entry.meta:
                     self.cash_securities_map[entry.currency] = entry.meta[EQUIVALENT_CURRENCY]
```

**Comment by scanta2** [comment]
@Zburatorul Thank you.
The latest ofx downloads I've got from Fidelity seem to have been corrected, but your fix looks OK to me.
