### ISSUE TITLE
Import of OFX CHECKNUM tag fails for a non-numeric value

### ISSUE THREAD

**Issue by gpaulissen** [jbms/beancount-import#44]
When processing my OFX file it fails with this error:

Traceback (most recent call last):
  File "C:\Users\gjpau\AppData\Local\Programs\Python\Python38\lib\site-packages\beancount\core\number.py", line 96, in D
    return Decimal(_CLEAN_NUMBER_RE.sub('', strord))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "c:\users\gjpau\documents\github\beancount-import\beancount_import\source\ofx.py", line 1394, in prepare
    state.get_accounts_and_entries()
  File "c:\users\gjpau\documents\github\beancount-import\beancount_import\source\ofx.py", line 1249, in get_accounts_and_entries
    statement.get_entries(self)
  File "c:\users\gjpau\documents\github\beancount-import\beancount_import\source\ofx.py", line 843, in get_entries
    posting_meta[CHECK_KEY] = D(stripped_checknum)
  File "C:\Users\gjpau\AppData\Local\Programs\Python\Python38\lib\site-packages\beancount\core\number.py", line 104, in D
    raise ValueError("Impossible to create Decimal instance from {!s}: {}".format(
ValueError: Impossible to create Decimal instance from 8OOMBV: [<class 'decimal.ConversionSyntax'>]
> c:\users\gjpau\appdata\local\programs\python\python38\lib\site-packages\beancount\core\number.py(104)D()
-> raise ValueError("Impossible to create Decimal instance from {!s}: {}".format(

When I comment all <CHECKNUM> tags the import succeeds.

The failing tag is: <CHECKNUM>08OOMBV

I have read the latest OFX specification that says a number of format A-12. However the A just means any UTF-8 character.

---

<CHECKNUM> Check (or other reference) number, A-12

---

Character fields are identified with a data type of “A-n”, where n is the maximum number of allowed
Unicode characters.
Note: n refers to the number of characters in the resultant string. Each multi-byte or encoded
character counts as a single character. UTF-8 encodes “high” Latin-1 characters (decimal 128-
255) using two bytes, and double-byte characters using three bytes. In addition, XML encodes
ampersands, less-than symbols, greater-than symbols, and spaces (where required) using multicharacter escape strings (see section 2.3.1.1). Therefore, an element of type A-40 may require
more than 40 bytes in a UTF-8-encoded XML stream.

**Comment by jbms** [comment]
I was using the decimal conversion to strip zero padding, but it looks like the code needs to be modified to treat the check numbers as strings instead, but still strip leading zeros.

Are you able to prepare a patch?
