### ISSUE TITLE
Paypal issue downloading transactions

### ISSUE THREAD

**Issue by ikwtif** [jbms/beancount-import#68]
Not sure what happened, but downloading paypal transactions stopped working for me. This still worked around 3 months ago.
command I'm using
`python -m finance_dl.cli --config-module paypal_finance_dl_config --config paypal`

error message, which I assume has to do with the json response
```DevTools listening on ws://127.0.0.1:53397/devtools/browser/2be1980f-5c6f-44e8-a13f-10db764e72bd
 --connect=http://127.0.0.1:53380 --session-id=be26bf0a500b64bd1208b16fa9765955
2020-09-27 19:09:38,338 paypal.py:136 [INFO] Finding username field
2020-09-27 19:09:38,358 paypal.py:139 [INFO] Entering username
2020-09-27 19:09:38,427 paypal.py:142 [INFO] Finding password field
2020-09-27 19:09:38,969 paypal.py:145 [INFO] Entering password
2020-09-27 19:09:42,974 paypal.py:149 [INFO] Logged in
2020-09-27 19:09:42,975 paypal.py:175 [INFO] Getting transaction list
2020-09-27 19:09:42,976 paypal.py:163 [INFO] Getting CSRF token
[16860:14784:0927/190945.479:ERROR:device_event_log_impl.cc(208)] [19:09:45.479] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
Traceback (most recent call last):
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\scrape_lib.py", line 402, in retry
    return func()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\scrape_lib.py", line 422, in fetch
    scraper.run()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 246, in run
    self.save_transactions()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 189, in save_transactions
    transaction_list = self.get_transaction_list()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 184, in get_transaction_list
    j = resp.json()
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Dieter\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dieter\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\cli.py", line 91, in <module>
    main()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\cli.py", line 87, in main
    module.run(**spec)
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 250, in run
    scrape_lib.run_with_scraper(Scraper, **kwargs)
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\scrape_lib.py", line 424, in run_with_scraper
    retry(fetch)
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\scrape_lib.py", line 402, in retry
    return func()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\scrape_lib.py", line 422, in fetch
    scraper.run()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 246, in run
    self.save_transactions()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 189, in save_transactions
    transaction_list = self.get_transaction_list()
  File "d:\documenten\coding\import beancount\finance-dl\finance_dl\paypal.py", line 184, in get_transaction_list
    j = resp.json()
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "D:\Documenten\coding\Import Beancount\beancount-import\env\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by ikwtif** [comment]
Nevermind, wrote on the wrong repo
